name: Test and Lint

on: [push]

jobs:
  test-and-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        # goのセットアップ
        - name: Set up golang
          uses: actions/setup-go@v4
          with:
            go-version: '>=1.20'
        # staticcheckインストール
        - name: Install staticcheck
          run: go install honnef.co/go/tools/cmd/staticcheck@latest
        # build
        - name: Build
          run: go build
        # test
        - name: Test
          run: go test ./...
        # 静的解析
        - name: Staticcheck
          run: staticcheck ./...