name: Test and Lint

on: [push]

jobs:
  test-and-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Set up golang
          uses: actions/setup-go@v4
          with:
            go-version-file: go.mod
            cache: true
        - name: Install staticcheck
          run: |
            if ! command -v staticcheck &> /dev/null
            then
              go install honnef.co/go/tools/cmd/staticcheck@latest
            fi
          shell: bash
        - name: Build
          run: go build
        - name: Test
          run: go test ./...
        - name: Staticcheck
          run: staticcheck ./...